stages:
  fetch_data:
    cmd: python fetch_weather.py
    deps:
    - fetch_weather.py
    outs:
    - raw_data.csv
  preprocess_data:
    cmd: python preprocess.py
    deps:
    - preprocess.py
    - raw_data.csv
    outs:
    - processed_data.csv
  train_model:
    cmd: python train_model.py
    deps:
    - processed_data.csv
    - train_model.py
    outs:
    - model.pkl
